import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StoreProvider from '@/components/shared/stores/RootStoreProvider';
import { getServerSession } from 'next-auth/next';
import Providers from '@/components/shared/providers/SessionProvider';
import './globals.css';
import { authConfig } from '@/components/shared/configs/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig);
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers session={session}>
          <StoreProvider>{children}</StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
